In [36]:
import numpy as np
import pandas as pd

#grid = np.zeros( (6,6), dtype = int )

# this part is just setting up a test grid, with which to try out your pretty printer
#aword = 'decaf'

#x = 0   # where to put it
#y = 3

#for letter in aword:
    #grid[ (y, x) ] = ord(letter) - 96
    #x += 1
    #if (x >= 6):
        #break   # don't go outside the grid!

#print(grid)

In [60]:
def convert(num):
    letter = ''
    if(num == 0):
        letter = ' '
    elif(num >= 1 and num <= 6):
        letter = chr(num+96)
    return letter

In [61]:
def putHoriz(string, grid, x, y):
    originalGrid = grid
    for letter in string:
        if(grid[(y,x)] != 0 and grid[(y,x)] != ord(letter)-96):
            return originalGrid
            
        grid[ (y, x) ] = ord(letter) - 96
        x += 1
    return grid

In [62]:
def putVert(string, grid, x, y):
    originalGrid = grid
    for letter in aword:
        if(grid[(y,x)] != 0 and grid[(y,x)] != ord(letter)-96):
            return originalGrid
        
        grid[ (y, x) ] = ord(letter) - 96
        y += 1
    return grid

In [66]:
import random
grid = np.zeros( (6,6), dtype = int )
wordlist = [ 'faced', 'decaf', 'fade', 'face', 'deaf', 'dace', 'cafe', 'cade', 'bead', 'bade', 'aced', 'abed', 'fed', 'fad', 'fab', 'def', 'deb', 'dab', 'cad', 'cab', 'bed', 'bad', 'ace' ]

count = 0

while(count<5):
    w = int(len(wordlist) * random.random())
    print('Picking word number', w, 'which is', wordlist[w])

    x = int(6 * random.random())
    y = int(6 * random.random())

    print('Try to put', wordlist[w], 'at', x, y)
    fit_horiz = True
    fit_vert = True
    if(x + len(wordlist[w])>=6):
        print('The word does not fit horizontally')
        fit_horiz = False

    if(int(y) + len(wordlist[w])>=6):
        print('The word does not fit vertically')
        fit_vert = False

    if(fit_horiz == False and fit_vert == False):
        print('The word does not fit anywhere :(')
        
    if(fit_horiz== True):
        grid = putHoriz(wordlist[w], grid, x, y)
    if(fit_vert == True):
        grid = putVert(wordlist[w], grid, x, y)
        
    print(grid)
        
    count+=1

Picking word number 2 which is fade
Try to put fade at 2 5
The word does not fit vertically
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 6 1 4 5]]
Picking word number 7 which is cade
Try to put cade at 1 1
[[0 0 0 0 0 0]
 [0 3 1 4 5 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 6 1 4 5]]
Picking word number 6 which is cafe
Try to put cafe at 3 0
The word does not fit horizontally
[[0 0 0 4 0 0]
 [0 3 1 4 5 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 6 1 4 5]]
Picking word number 5 which is dace
Try to put dace at 2 2
[[0 0 0 4 0 0]
 [0 3 1 4 5 0]
 [0 0 4 1 3 5]
 [0 0 5 0 0 0]
 [0 0 3 0 0 0]
 [0 0 6 1 4 5]]
Picking word number 5 which is dace
Try to put dace at 0 2


IndexError: index 6 is out of bounds for axis 0 with size 6

In [67]:
def prettyprint(df):   
    for row in df:
        row_str = ''
        for num in row:
            row_str = row_str + convert(num) + ' '
        print(row_str)
        
    

In [68]:
prettyprint(grid)
print(grid)

      d     
  c a d e   
d a d a c e 
e   e       
c   c       
a   f a d e 
[[0 0 0 4 0 0]
 [0 3 1 4 5 0]
 [4 1 4 1 3 5]
 [5 0 5 0 0 0]
 [3 0 3 0 0 0]
 [1 0 6 1 4 5]]
