In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
odd_bool = arr%2!=0
oddArr = arr[odd_bool]
print(oddArr)

[1 3 5 7 9]


In [5]:
arr = np.arange(1,10)

oddArr = np.where(arr%2 == 1, -1, arr)

arr2 = np.arange(11,20)
arr2 = np.where(oddArr==-1, -1, arr2)
print(arr2)

[-1 12 -1 14 -1 16 -1 18 -1]


In [8]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)




(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [16]:
c = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))


c = c[index]

print(c)

[ 6  9 10]


In [35]:
d = np.arange(6).reshape(3,2)
print(d)

e = np.array([d[:,0],d[:,1]]).reshape(2,3)
print()
print(e)

[[0 1]
 [2 3]
 [4 5]]

[[0 2 4]
 [1 3 5]]


In [37]:
d = np.arange(6).reshape(3,2)
d = d[[1,0,2],:]
print(d)



[[2 3]
 [0 1]
 [4 5]]
